name: hauth
version: '0.1.0.0'
category: Web
author: Ecky Putrady
maintainer: eckyp@example.com
copyright: 2017 Ecky Putrady
license: BSD3
github: githubuser/hauth
extra-source-files:
- README.md

default-extensions:
- OverloadedStrings
- QuasiQuotes
- GeneralizedNewtypeDeriving
- ConstraintKinds
- FlexibleContexts
- TemplateHaskell
- LambdaCase

ghc-options:
- -Wall
- -Werror
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
  - NoImplicitPrelude
  dependencies:
  - classy-prelude
  - base
  - pcre-heavy
  - time-lens
  - time
  - aeson
  - mtl
  - string-random
  - data-has
  - katip
  - postgresql-simple
  - postgresql-simple-migration
  - resource-pool
  - hedis
  - amqp
  - http-types
  - scotty
  - cookie
  - wai
  - wai-extra
  - blaze-builder
  - digestive-functors
  - digestive-functors-aeson
  - blaze-html
  - digestive-functors-blaze
  - digestive-functors-scotty
  - wai-middleware-static
  - warp
  - http-client
  - http-client-tls
  - template-haskell
executables:
  hauth-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hauth
    - base
tests:
  hauth-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - NoImplicitPrelude
    dependencies:
    - classy-prelude
    - base
    - hauth
    - hspec
    - hspec-wai
    - hspec-wai-json
    - process
    - postgresql-simple
    - string-random
    - hedis
    - pcre-heavy
    - katip
    - http-types
    - wai
